### ISSUE TITLE
AWS AMI SSH not working out of the box

### ISSUE THREAD

**Issue by darrensessions** [hydrajump/vyos-build-ami#2]
EC2: -----BEGIN FETCH SSH PUBLIC KEY-----.
EC2: Requesting ssh public key from EC2 instance metadata.
EC2: Downloaded ssh public key from EC2 instance metadata.
EC2: Loaded ssh public key for user vyos.
###### ################################################################### 100.0%

Unknown key type AAAAB3NzaC1yc2EAAAADAQABAAABAQDH9lrtekBNEjVnyIdVgWKbut/IHJ8pHDm5NKPbAizlETMMI+3iraBPqEV7l8p3i1aXLeNYvBESee/9J9pJe5lKLMSpgpQSRTEvT4br8r4m7KNmHRVna47heCSM6jZjfd1y0ctpNRnkaEcVxesVVIookSJpBDg/ok8h4DxMuFgmknvJrFFRCwdSUTX0pyN4IEuBRPqxXPXrHvSA5vGQjjzhXwCrPGFSq2GevyL+jv6npf74qG2SKubWY6GmqN8Oxeb+2vM12gYlm6Ppfoz21WLpLUbOYPxzmtUdxTveVNxeriOv6x5HeB2bW3vnrZ6sKPTBBOMteKj3cq1WKGKPahZh : must be ssh-rsa or ssh-dss
Saving configuration to '/config/config.boot'...
Done
EC2: -----END FETCH SSH PUBLIC KEY-----.

**Comment by darrensessions** [comment]
Pull request submitted.

**Comment by TaiSHiNet** [comment]
For those who might run into this: key name should not contain spaces
